### ISSUE TITLE
设置宽高怎么没用

### ISSUE THREAD

**Issue by yfjl** [PanJiaChen/electron-vue-admin#13]
控制窗口大小  设置不了

**Comment by PanJiaChen** [comment]
控制窗指的是什么？
`BrowserWindow`的`width`么？

**Comment by yfjl** [comment]
是的 设置窗口最小宽度没效果

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/electron-vue-admin/blob/64dfb93d7e77d71c40d01e7f536b5af9301a531e/src/main/index.js#L21
测试了一下，没什么问题啊。

**Comment by yfjl** [comment]
设置minWidth:1000, 仍然可以把宽度拖到小于1000
