### ISSUE TITLE
Timeout exceed when trying to log in.

### ISSUE THREAD

**Issue by mrdionjr** [PanJiaChen/electron-vue-admin#17]
When I try to sign in using the default credentials (admin/admin), the request fails after a few seconds with a `timeout of 15000ms exceeded` error. This happen both in the web app and the desktop app.

**Comment by PanJiaChen** [comment]
Because using [easy-mock](https://github.com/easy-mock/easy-mock) in the project to simulate data, But it can sometimes be unstable. You can try again now.

**Comment by mrdionjr** [comment]
Thanks! It works now.
