### ISSUE TITLE
svg图片失效

### ISSUE THREAD

**Issue by dtboy1995** [PanJiaChen/electron-vue-admin#27]
感谢作者, svg图片失效

**Comment by dtboy1995** [comment]
不好意思，我自己配置的问题。

**Comment by inchtime** [comment]
我也是svg图片失效，请问你是怎么解决的

**Comment by dtboy1995** [comment]
你要是出错应该是你没有直接clone他的项目吧，其实兄弟你仔细看配置文件就行，弄成和他项目一样即可

**Comment by yanwenjia** [comment]
我也是svg不显示，请问大佬怎么解决的

**Comment by dtboy1995** [comment]
@yanwenjia 兄弟你看下你的webpack配置，里面是不是缺少svg-loader

**Comment by dtboy1995** [comment]
https://github.com/PanJiaChen/electron-vue-admin/blob/master/.electron-vue/webpack.renderer.config.js#L79看下这里重点

**Comment by yanwenjia** [comment]
@dtboy1995 感谢大佬 我看下
