### ISSUE TITLE
为什么不能打包啊？

### ISSUE THREAD

**Issue by 11003** [PanJiaChen/electron-vue-admin#71]
![image](https://user-images.githubusercontent.com/35055270/119222187-a9b00000-bb25-11eb-8348-c1f6a5aa553d.png)

**Comment by sorry510** [comment]
不要使用cnpm，换用yarn就不会报这个错了

**Comment by 11003** [comment]
> 不要使用cnpm，换用yarn就不会报这个错了
谢谢！
