### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by wangxueyou110** [PanJiaChen/electron-vue-admin#8]
![image](https://user-images.githubusercontent.com/30291910/38913306-a0596a4e-430c-11e8-859d-433d2f299c07.png)
这个是npm i的时候，下面是dev的时候
![image](https://user-images.githubusercontent.com/30291910/38913320-b1eb499e-430c-11e8-8226-1e082182860a.png)
![image](https://user-images.githubusercontent.com/30291910/38913339-caf3e8d8-430c-11e8-950a-42393c48f53c.png)

**Comment by PanJiaChen** [comment]
报错信息已经很完整了，请自行解决。
